apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ngnix2
  name: ngnix2
spec:
  containers:
  - image: nginx
    name: ngnix2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
